version: "3.8"

services:
    postgres:
        image: postgres:15-alpine
        container_name: room-scheduler-db
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=rooms_db
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
        volumes:
            - postgres_data:/var/lib/postgresql/postgres_data

volumes:
    postgres_data:
